//
// *****************************************************************************
// Copyright(c) 2017-2024 Juphoon System Software Co., LTD. All rights reserved.
// *****************************************************************************
//
// Auto generated from: ObjectLocator.def
// Warning: do not edit this file.
//

#ifndef __Common_ObjectLocatorAgent_h
#define __Common_ObjectLocatorAgent_h

#include "Common/ObjectLocatorPub.h"
#include <functional>

namespace Common
{

class CommonAPI ObjectLocatorAgent : public Common::Agent
{
public:
    ObjectLocatorAgent(int zero = 0) : Common::Agent(zero) {}
    ObjectLocatorAgent(const Common::Agent& agent) : Common::Agent(agent) {}
    ObjectLocatorAgent(const Common::ObjectAgentPtr& agent) : Common::Agent(agent) {}

    bool locateObject(const Common::String& oid,bool nextTime,Common::String& aid,const Common::CallParamsPtr& __params = 0) const;
    void locateObject_begin(const Common::AgentAsyncPtr& __async,const Common::String& oid,bool nextTime,const Common::CallParamsPtr& __params = 0,const Common::ObjectPtr& __userdata = 0) const throw();
    static bool locateObject_end(int __rslt,const Common::IputStreamPtr& __iput,Common::String& aid);
};

};//namespace: Common

#endif //__Common_ObjectLocatorAgent_h
