//
// *****************************************************************************
// Copyright(c) 2017-2022 Juphoon System Software Co., LTD. All rights reserved.
// *****************************************************************************
//
// Auto generated from: ObjectLocator.def
// Warning: do not edit this file.
//

#ifndef __Common_ObjectLocatorPub_h
#define __Common_ObjectLocatorPub_h

#include "Common/Common.h"

namespace Common
{

};//namespace: Common

#endif //__Common_ObjectLocatorPub_h
