//
// *****************************************************************************
// Copyright(c) 2017-2022 Juphoon System Software Co., LTD. All rights reserved.
// *****************************************************************************
//
// Auto generated from: ObjectLocator.def
// Warning: do not edit this file.
//

#ifndef __Common_ObjectLocatorServer_h
#define __Common_ObjectLocatorServer_h

#include "Common/ObjectLocatorPub.h"

namespace Common
{

class CommonAPI ObjectLocatorServer : virtual public Common::ObjectServer
{
public:
    virtual bool __ex(const Common::ServerCallPtr& __call,const Common::String& __cmd,const Common::IputStreamPtr& __iput);

    virtual void locateObject_begin(const Common::ServerCallPtr& __call,const Common::String& oid,bool nextTime) = 0;

    static void locateObject_end(const Common::ServerCallPtr& __call,bool __ret,const Common::String& aid);

    static inline void locateObject_end(const Common::ServerCallPtr &__call,const Common::CallError &error)
    {
        __call->setError(error);
        locateObject_end(__call,false,"");
    }

private:
    void __cmd_locateObject(const Common::ServerCallPtr& __call,const Common::IputStreamPtr& __iput);
};

};//namespace: Common

#endif //__Common_ObjectLocatorServer_h
