//
// *****************************************************************************
// Copyright(c) 2017-2022 Juphoon System Software Co., LTD. All rights reserved.
// *****************************************************************************
//
// Auto generated from: RouterDb.def
// Warning: do not edit this file.
//

#ifndef __Common_RouterDbAgent_h
#define __Common_RouterDbAgent_h

#include "Common/RouterDbPub.h"

namespace Common
{

class CommonAPI RouterDbAgent : public Common::Agent
{
public:
    RouterDbAgent(int zero = 0) : Common::Agent(zero) {}
    RouterDbAgent(const Common::Agent& agent) : Common::Agent(agent) {}
    RouterDbAgent(const Common::ObjectAgentPtr& agent) : Common::Agent(agent) {}

    bool recordRouter(int routerId,const Common::String& host,const Common::String& name,const Common::RouterStatistics& statistics,const Common::RouterQualityMap& qualitys,const Common::CallParamsPtr& __params = 0) const throw();
    void recordRouter_begin(const Common::AgentAsyncPtr& __async,int routerId,const Common::String& host,const Common::String& name,const Common::RouterStatistics& statistics,const Common::RouterQualityMap& qualitys,const Common::CallParamsPtr& __params = 0,const Common::ObjectPtr& __userdata = 0) const throw();
    static bool recordRouter_end(int __rslt,const Common::IputStreamPtr& __iput) throw();

    bool recordClient(int routerId,int clientId,const Common::String& host,double longitude,double latitude,const Common::ClientQuality& sendQuality,const Common::ClientQuality& recvQuality,const Common::CallParamsPtr& __params = 0) const throw();
    void recordClient_begin(const Common::AgentAsyncPtr& __async,int routerId,int clientId,const Common::String& host,double longitude,double latitude,const Common::ClientQuality& sendQuality,const Common::ClientQuality& recvQuality,const Common::CallParamsPtr& __params = 0,const Common::ObjectPtr& __userdata = 0) const throw();
    static bool recordClient_end(int __rslt,const Common::IputStreamPtr& __iput) throw();
};

};//namespace: Common

#endif //__Common_RouterDbAgent_h
