//
// *****************************************************************************
// Copyright(c) 2017-2022 Juphoon System Software Co., LTD. All rights reserved.
// *****************************************************************************
//
// Auto generated from: Global.def
// Warning: do not edit this file.
//

#ifndef __Global_GlobalAgent_h
#define __Global_GlobalAgent_h

#include "Global/GlobalPub.h"

namespace Global
{

/* #ErrorRecord */
class ErrRecordAgent : public Common::Agent
{
public:
    ErrRecordAgent(int zero = 0) : Common::Agent(zero) {}
    ErrRecordAgent(const Common::Agent& agent) : Common::Agent(agent) {}
    ErrRecordAgent(const Common::ObjectAgentPtr& agent) : Common::Agent(agent) {}

    bool record(const Global::ErrRecords& errRecords,const Common::CallParamsPtr& __params = 0) const throw();
    void record_begin(const Common::AgentAsyncPtr& __async,const Global::ErrRecords& errRecords,const Common::CallParamsPtr& __params = 0,const Common::ObjectPtr& __userdata = 0) const throw();
    static bool record_end(int __rslt,const Common::IputStreamPtr& __iput) throw();
};

/* GlobalTime/#GlobalTime */
class GlobalTimeAgent : public Common::Agent
{
public:
    GlobalTimeAgent(int zero = 0) : Common::Agent(zero) {}
    GlobalTimeAgent(const Common::Agent& agent) : Common::Agent(agent) {}
    GlobalTimeAgent(const Common::ObjectAgentPtr& agent) : Common::Agent(agent) {}

    bool globalTime(Common::Long& time,const Common::CallParamsPtr& __params = 0) const throw();
    void globalTime_begin(const Common::AgentAsyncPtr& __async,const Common::CallParamsPtr& __params = 0,const Common::ObjectPtr& __userdata = 0) const throw();
    static bool globalTime_end(int __rslt,const Common::IputStreamPtr& __iput,Common::Long& time) throw();
};

};//namespace: Global

#endif //__Global_GlobalAgent_h
