//
// *****************************************************************************
// Copyright(c) 2017-2022 Juphoon System Software Co., LTD. All rights reserved.
// *****************************************************************************
//
// Auto generated from: Global.def
// Warning: do not edit this file.
//

#include "Global/GlobalPub.h"

namespace Global
{
void __write_ErrRecords(const Common::OputStreamPtr& __oput,const Global::ErrRecords& __obj)
{
    __oput->write((int)__obj.size());
    vector<Common::StrStrMap>::const_iterator it1;
    for (it1 = __obj.begin();it1 != __obj.end();it1++)
        Common::__write_StrStrMap(__oput,*it1);
}

void __read_ErrRecords(const Common::IputStreamPtr& __iput,Global::ErrRecords& __obj)
{
    __obj.clear();
    int size;__iput->read(size);
    for (int i=0;i< size;i++)
    {
        Common::StrStrMap m;
        Common::__read_StrStrMap(__iput,m);
        __obj.push_back(m);
    }
}

void __textWrite_ErrRecords(const Common::OputStreamPtr& __oput,const Common::String& __name,const Global::ErrRecords& __obj)
{
    __oput->textArray(__name);
    vector<Common::StrStrMap>::const_iterator it1;
    for (it1 = __obj.begin();it1 != __obj.end();it1++)
        Common::__textWrite_StrStrMap(__oput,__name,*it1);
}

bool __textRead_ErrRecords(const Common::IputStreamPtr& __iput,const Common::String& __name,Global::ErrRecords& __obj)
{
    __obj.clear();
    int size = __iput->textCount(__name);
    for (int i=0;i<size;i++)
    {
        Common::StrStrMap m;
        if (Common::__textRead_StrStrMap(__iput,__name,m,i))
            __obj.push_back(m);
    }
    return true;
}


};//namespace: Global
