//
// *****************************************************************************
// Copyright(c) 2017-2022 Juphoon System Software Co., LTD. All rights reserved.
// *****************************************************************************
//
// Auto generated from: Global.def
// Warning: do not edit this file.
//

#ifndef __Global_GlobalPub_h
#define __Global_GlobalPub_h

#include "Common/Common.h"
#include "Common/TypesPub.h"

namespace Global
{

typedef vector<Common::StrStrMap> ErrRecords;
void __write_ErrRecords(const Common::OputStreamPtr&,const Global::ErrRecords&);
void __read_ErrRecords(const Common::IputStreamPtr&,Global::ErrRecords&);
void __textWrite_ErrRecords(const Common::OputStreamPtr&,const Common::String&,const Global::ErrRecords&);
bool __textRead_ErrRecords(const Common::IputStreamPtr&,const Common::String&,Global::ErrRecords&);

};//namespace: Global

#endif //__Global_GlobalPub_h
